 trigger:
 - main

 pool: self-hosted-1

 variables:
   imageName: 'pipelines-javascript-docker'

 steps:
 - checkout: self

 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile